"""
Type Chart representation for Pokemon generation 6+.
Source: https://bulbapedia.bulbagarden.net/wiki/Type/Type_chart

Contains a damage multiplier lookup dictionary.
Form:
{
    attack type (str): {defending type : multiplier (float), ...},
    ...
}
(!) Lookup the defending type with .get(); if None is returned,
then there is no special case and the multiplier is assumed to be 1x.
"""

damage_multiplier = {
    "NORMAL": {"ghost": 0, "rock": 0.5, "steel": 0.5},
    "FIGHTING": {
        "normal": 2,
        "flying": 0.5,
        "poison": 0.5,
        "rock": 2,
        "bug": 0.5,
        "ghost": 0,
        "steel": 2,
        "psychic": 0.5,
        "ice": 2,
        "dark": 2,
        "fairy": 0.5,
    },
    "FLYING": {
        "fighting": 2,
        "rock": 0.5,
        "bug": 2,
        "steel": 0.5,
        "grass": 2,
        "electric": 0.5,
    },
    "POISON": {
        "poison": 0.5,
        "ground": 0.5,
        "rock": 0.5,
        "ghost": 0.5,
        "steel": 0,
        "grass": 2,
        "fairy": 2,
    },
    "GROUND": {
        "flying": 0,
        "poison": 2,
        "rock": 2,
        "bug": 0.5,
        "steel": 2,
        "fire": 2,
        "grass": 0.5,
        "electric": 2,
    },
    "ROCK": {
        "fighting": 0.5,
        "flying": 2,
        "ground": 0.5,
        "bug": 2,
        "steel": 0.5,
        "fire": 2,
        "ice": 2,
    },
    "BUG": {
        "fighting": 0.5,
        "flying": 0.5,
        "poison": 0.5,
        "ghost": 0.5,
        "steel": 0.5,
        "fire": 0.5,
        "grass": 2,
        "psychic": 2,
        "dark": 2,
        "fairy": 0.5,
    },
    "GHOST": {"normal": 0, "ghost": 2, "psychic": 2, "dark": 0.5},
    "STEEL": {
        "rock": 2,
        "steel": 0.5,
        "fire": 0.5,
        "water": 0.5,
        "electric": 0.5,
        "ice": 2,
        "fairy": 2,
    },
    "FIRE": {
        "rock": 0.5,
        "bug": 2,
        "steel": 2,
        "fire": 0.5,
        "water": 0.5,
        "grass": 2,
        "ice": 2,
        "dragon": 0.5,
    },
    "WATER": {
        "ground": 2,
        "rock": 2,
        "fire": 2,
        "water": 0.5,
        "grass": 0.5,
        "dragon": 0.5,
    },
    "GRASS": {
        "flying": 0.5,
        "poison": 0.5,
        "ground": 2,
        "rock": 2,
        "bug": 0.5,
        "steel": 0.5,
        "fire": 0.5,
        "water": 2,
        "grass": 0.5,
        "dragon": 0.5,
    },
    "ELECTRIC": {
        "flying": 2,
        "ground": 0,
        "water": 2,
        "grass": 0.5,
        "electric": 0.5,
        "dragon": 0.5,
    },
    "PSYCHIC": {"fighting": 2, "poison": 2, "steel": 0.5, "psychic": 0.5, "dark": 0},
    "ICE": {
        "flying": 2,
        "ground": 2,
        "steel": 0.5,
        "fire": 0.5,
        "water": 0.5,
        "grass": 2,
        "dragon": 2,
        "ice": 0.5,
    },
    "DRAGON": {"steel": 0.5, "dragon": 2, "fairy": 0},
    "DARK": {"fighting": 0.5, "ghost": 2, "psychic": 2, "dark": 0.5, "fairy": 0.5},
    "FAIRY": {
        "fighting": 2,
        "poison": 0.5,
        "steel": 0.5,
        "fire": 0.5,
        "dragon": 2,
        "dark": 2,
    },
}
